# Generated by Django 2.1.4 on 2018-12-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='email',
            field=models.EmailField(default='me@here.com', max_length=254),
        ),
    ]
