# Generated by Django 2.1.4 on 2018-12-10 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bage', '0002_auto_20181210_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='srq',
            name='srqNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='srq',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 14, 50, 54, 946241)),
        ),
    ]
